### ISSUE TITLE
[Palu] Exports de données brutes: ajouter l'heure de validation des rapports par le district sanitaire

### ISSUE THREAD

**Issue by alou** [yeleman/snisi#107]

**Comment by fadiga** [comment]
8269f94 Ajout au all_malariar_as_xls la colonne validated_on

**Comment by rgaudin** [comment]
deployé

**Comment by alou** [comment]
@fadiga received_on et validated_on ne sont pas dans le même format, ajoute une colonne auto validation

**Comment by fadiga** [comment]
dbfc712 
- Ajout colonne AUTO_VALIDATED.
- Harmonisation des dates.
