### ISSUE TITLE
Add new integrity check to Malaria Routine

### ISSUE THREAD

**Issue by rgaudin** [yeleman/snisi#2]
MEASURE requested a new integrity check : 

__confirmed = simple malaria cases + severe malaria cases__

It should replace the existing _confirmed >= simple malaria cases + severe malaria cases_

Modification should be done in:
* Monthly routine integrity checks.
* Epidemiology integrity checks.
* Monthly routine Excel template.
* Epidemiology weekly Excel template.
* Java Application.

**NB**: A roll-out of the modified tools is required afterwards. Please create an issue to track it once this is closed.

**Comment by rgaudin** [comment]
@fadiga ?

**Comment by fadiga** [comment]
Java Application is done.

**Comment by fadiga** [comment]
* Monthly routine Excel template.
* Epidemiology weekly Excel template.

Will be replaced by the Android Forms. No need to update.

**Comment by fadiga** [comment]
Correction du contrôle  integrity palu.
confirmé > simple + grave en confirmé != simple + grave.
