### ISSUE TITLE
Rapport non attendu à Madina/San

### ISSUE THREAD

**Issue by alou** [yeleman/snisi#24]
Pas de expected pour madina (FTK4) dans le district de san (KZF8)

**Comment by rgaudin** [comment]
@alou, merci de préparer le fichier move et d'ajouter au calendrier pour ajout le 1er mars sinon on va créer des expecteds pour Janvier (cf. #32)

**Comment by alou** [comment]
C'est fait

**Comment by rgaudin** [comment]
quel fichier ? Je vois pas l’évènement dans le calendrier non plus…

**Comment by rgaudin** [comment]
OK c'est bon
