### ISSUE TITLE
Création des villages

### ISSUE THREAD

**Issue by alou** [yeleman/snisi#35]
AIRE DE SANTÉ DE SAMAKELE Z6YP1
    BEGNENI
    TIOROBOUGOU

AIRE DE SANTÉ DE MADINA SACKO ZTHR1
    BAMBILA
    TOTA SOULEY SOW

AIRE DE SANTÉ DE BORON ZMTG3
    Soubala Makana

AIRE DE SANTÉ DE GUESSENE ZZAG0
    SOSSO

AIRE DE SANTÉ DE SEBETE ZKX34
    MADINA KONARE
    Sidonibougou
    N'Tomifing

AIRE DE SANTÉ DE OULENY ZA530
    BOUMBOUNDO
    MORIBOUGOU TRAORE

AIRE DE SANTÉ DE KEROUANE ZMDK8
    KOLODO
    GUESSEREBOUGOU
    KORONINDO

AIRE DE SANTÉ DE NTIELE Z6YX9
    Hamadila
    Bougouba
    Babara
    Koulera
    Yorobougou

AIRE DE SANTÉ DE BANAMBA CENTRAL ZS794
    DIASSANI
    Diatouroubougou
    KOUNA
    Tiontala
    Zambougou
    N'Galamadibi
    Sabalibougou
    Fadabougou
    Bougounina
    Kolondialan
    N'Ganouba
    Bamarobougou

AIRE DE SANTÉ DE BANCO ZMT96
    Founéna
    Toubala
    Djogo
    Fougouyé
    Fasséribougou
    Komobougou
    Klé
    Baoun
    Massafimbougou
    Kounabougou

AIRE DE SANTÉ DE FALAKONO ZCPP7
    N'djilla-Fignana
    N'tinimbougou
    Dantia

AIRE DE SANTÉ DE KOLA Z3R44
    Diero
    Gouana
    Gouendo

AIRE DE SANTÉ DE MASSIGUI ZAY64
    Bourouna
    Tabakoro
    Koumabougou
    Déniékoro

AIRE DE SANTÉ DE SERIBILA ZS6D3
    Sanandio

AIRE DE SANTÉ DE MABAN ZHH40
    Fah-Manacoungo
    Donobougou

AIRE DE SANTÉ DE NANGOLA Z3AX4
    FARACOROBOUGOU
    FARCOOROSOBA
    FARACORO

AIRE DE SANTÉ DE BELEKO SOBA ZSY70
    GUELEKOUN

AIRE DE SANTÉ DE DJELE ZTXB9
    ZAMBOUGOU
    NDJIBOUGOU
    KOKOUN
    N'THIADOUGOUTIGILA

AIRE DE SANTÉ DE KONI Z78G6
    FADIOLA

AIRE DE SANTÉ DE KERELA Z4C29
    FOLONDA

AIRE DE SANTÉ DE FANA CENTRAL ZTJ65
    MISSANGO

AIRE DE SANTÉ DE KOTOULA ZDMM1
    NGOLOBALA

AIRE DE SANTÉ DE KENIEGOUE ZKWE1
    Sombo
    Tèguè-Coura
    Tèguè-Coro
    Koblani
    Koflatiè
    Farba-Cougo

AIRE DE SANTÉ DE NARENA ZJYE9
    Kéniéma
    Samalofira
    Sébécourani
    Socourani

AIRE DE SANTÉ DE KARAN Z3TH8
    Kobamian
    Faraguè
    Landé

AIRE DE SANTÉ DE KENIEBA-KANGABA ZS2B7
    Sakoro
    Mansaya
    Nougani
    Tomodo-Komakara
    Kourémalé

AIRE DE SANTÉ DE TOMBOLA ZFEH9
    Danga
    Banancoro
    Samaya
    djoulafoundo
    Sananfara

AIRE DE SANTÉ DE FIGUIRATOMO ZJCH1
    Figuira-Coro
    Kondona
    Danga-Coro
    Faragouania
    N'Molodjèbougou
    Kolendjiguè

AIRE DE SANTÉ DE SALAMALE ZA9Y9
    Balanzan
    Farada
    Sakolenda
    Tambala
    Tinfra

AIRE DE SANTÉ DE KANGABA CENTRAL ZP4P3
    Dambala
    Gassala
    Dèguèla
    Kéla
    Balandougou 2
    Hamdallaye

AIRE DE SANTÉ DE SELEFOUGOU ZA679
    Balandougou 1
    Sanankoro
    Fanzan
    Fouh
    Sélin

AIRE DE SANTÉ DE BALAN-BAKAMA Z9F45
    Djolibani
    Soléfara
    Namagana
    Mambila
    Komana-Kouta

AIRE DE SANTÉ DE SABOUGOU Z7RT7
    Fonflébougou
    Tiorikabougou

AIRE DE SANTÉ DE SERIWALA ZDAW1
    Kiléladji
    N'Globougou

AIRE DE SANTÉ DE DIDIENI ZK2N6
    Bassabougou

AIRE DE SANTÉ DE OUOLODO ZECY8
    Sababougou
    Diatroubougou

AIRE DE SANTÉ DE TOUSSANA ZRAZ7
    Gonjibougou

AIRE DE SANTÉ DE KOUMI ZGA96
    Béléniko

AIRE DE SANTÉ DE MANTA Z73Y7
    Zambougou

AIRE DE SANTÉ DE SONKENIE Z8B59
    Ouolodo

AIRE DE SANTÉ DE SAMANTARA ZZ6H0
    Kodialan
    Namantiguila

AIRE DE SANTÉ DE DOUBABOUGOU ZAD75
    Niarébougou

AIRE DE SANTÉ DE NONKON Z9522
    Koria
    Nokala
    Bilissabougou
    N’Gabacoro D
    Bouloukouma
    Djiribabougou
    Kéna
    Markala
    Bougoudiana
    Wolodiédo
    Finké Siyoro
    Sikoro Nonkon
    Kossoumalé
    Tienko
    Niatoumana
    Sinébougou

AIRE DE SANTÉ DE NOSSOMBOUGOU ZE490
    Guéssébougou
    Mintikila
    Kodian
    Pintiérébougou
    N’Golobougou
    Kénékolo
    Diarrabougou
    Plokobougou
    Warala
    Kamaga

AIRE DE SANTÉ DE SEBECORO 1 ZZ3B5
    Nababougou

AIRE DE SANTÉ DE KOLOKANI CENTRAL ZZGH3
    Gouanobougou
    Nionakabougou
    Niénèkola
    Koundogoni
    Djadjirila
    Sanankoroni
    Sanamblé Noumoubougou
    Gombabougou
    Sirakoroni
    Kouloukoroni
    Sanamblé Ouest
    Sido
    Filawerè
    Sirafla
    Korotikiya

AIRE DE SANTÉ DE GOUMBOU ZCJM4
    Kaloumba

AIRE DE SANTÉ DE NARA CSREF Z7R24
    Toumoudrane
    Kabida Bambara
    Kabida Soniké
    Berzack
    Berguénaré
    Mabrouck
    Guirdé
    Kabida Maure
    Kebane Soninké
    Daye
    Tindié
    Ker El gagny
    Tourou Daya
    Madinacoura
    Lambassita
    Diewaye

AIRE DE SANTÉ DE DILLY ZZ7A1
    N'tomikôro
    Souleymane

AIRE DE SANTÉ DE DALLY ZZF29
    Sambé
    Kamatingué
    Siramané
    Kolal
    Kobala
    Mounalé Hamdallaye
    Tanganagaba
    Diongodji
    Mounalé Sareyoro
    Troumé Boulol

AIRE DE SANTÉ DE ALLASSO Z3G84
    Dina Coura

AIRE DE SANTÉ DE MOURDIAH ZPHC5
    Kolla

AIRE DE SANTÉ DE DALIBOUGOU Z7XA5
    Naouléna

AIRE DE SANTÉ DE MADINA KAGORO Z75A0
    Grindingué
    Madina Sylla
    Namatiguila
    N'tomono
    Toumoula
    Yerkoulé
    Serkole-Seguell
    Nantiala
    Tallan

AIRE DE SANTÉ DE GUIRE Z7DG4
    Djéwoye
    Loady Cherif
    Benko
    Tablanko
    N'gabakôro
    Nioko
    N'tjibougou
    Bangolo
    Mabrouk El Mane
    Mabrouk El hassane
    Sabremamy
    Dikoni

AIRE DE SANTÉ DE FALLOU Z9E75
    Zangarbala
    Karfabougou

AIRE DE SANTÉ DE DIGAN Z6JE8
    Tiéssébougou
    Batribougou

AIRE DE SANTÉ DE DJIGUE Z69M3
    Kitiola
    N'gaï
    Kalbana
    Sibitimbougou
    N'téguédo
    Bouabougou
    N'golobala
    Djéfala

AIRE DE SANTÉ DE BALLE Z3N48
    Barsafé
    Korokossié
    Bassaka
    Mounta
    Niarkassalambé
    Ouaïnka
    Diguigna
    Dinah
    Hamdallaye
    Palali
    Dioka
    Bouaré Tougoumé

AIRE DE SANTÉ DE BOULAL ZERW4
    Fofara
    Bagoïni

AIRE DE SANTÉ DE WAOUROU ZGAF4
    Dombakobe
    Kharguade
    Sobougou
    N'tiamabougou

AIRE DE SANTÉ DE BINEOU NIAKATE Z2XR2
    Binéou-Fissourou
    Bédiatt
    Missira Samoura
    Sami
    Djingué
    Djingriyé
    Bagué
    Daradia
    Takaye

AIRE DE SANTÉ DE ASACOOUEL (OUELESSEBOUGOU CENTRAL) ZEPM8
    TENTOUBOUGOU
    SEGESSONA
    ZELANI
    MORODJANBOUG
    MANA
    N/KOROBOUGOU
    SOUNSOUNKORO
    TAMALA
    FEREKOROBA
    TENMANBOUGOU
    SIKORODJITOUM
    TENTOUKORO
    DIALAKORODJIM
    ZANBOUGOUD
    M'PIEBOUGOU
    SIMIDJI
    M'PANA
    MANABOUGOU
    MOLOBALA
    BLADIE
    DAGABO
    DONGORONA
    BAGA
    LENA
    SOUGOULA
    KORONA

AIRE DE SANTÉ DE FARABA-KATI ZHAH3
    Warmadiana
    Siramana

AIRE DE SANTÉ DE SANANKORO-DJITOUMOU ZHFF8
    Satiguibougou

AIRE DE SANTÉ DE SAFE BOUGOULA Z86R5
    Karako

AIRE DE SANTÉ DE BENEKO ZJYP7
    Dianikoro

AIRE DE SANTÉ DE DIALAKOROBA ZA8F4
    Maraco

AIRE DE SANTÉ DE TIAKADOUGOU DIALACORO ZX7G0
    Mayaka

**Comment by rgaudin** [comment]
et alors ? c'est fait ou pas ? c'etait dans la derniere update?

**Comment by alou** [comment]
c'est fait
