### ISSUE TITLE
Snisi: création de privilège moniteur

### ISSUE THREAD

**Issue by drcamara** [yeleman/snisi#57]
* peut voir la  progression de la collecte
* peut voir toutes les données

**Comment by drcamara** [comment]
@alou quant -est ce que ça sera fait?

**Comment by alou** [comment]
@drcamara bientot

**Comment by rgaudin** [comment]
Attention, le tag urgent c'est uniquement ce qui est urgent. Par définition, ne s'applique pas à une nouvelle fonctionnalité.

@alou je pense que ce doit être un privilège et non un rôle non?

**Comment by drcamara** [comment]
Bien reçu!

**Comment by alou** [comment]
J'ai changé le titre

**Comment by rgaudin** [comment]
Fait et déployé.
