### ISSUE TITLE
PNLC: ajustement du rôle central 

### ISSUE THREAD

**Issue by drcamara** [yeleman/snisi#60]
A l'issue de notre recontre avec seigthsavers il est ressorti que:
* les agents du PNLC n'avaient pas accès à toutes les données: après verification effectivement je me suis rendu compte qu'ils avaient le rôle central mais pas sur le Mali. 
* Sur la plateforme au niveau de la partie création de compte il n' y a pas de rôle central sur le Mali.
Donc je proposerai que dans le système tous ceux  qui  ont le profil central voient toutes les données concernant leur projet respectif. Car dans le classique de santé il existe aussi le niveau central (national), intermediaire (regional) et operationnel (district).
* Aussi au niveau de l'annuaire certaines requêtes ne passent pas bien:   
exempl: quand tu prend  Réduction backlog TT/ central     j'ai remarqué que tous ceux qui ont le profil central ne sortent pas par rapport à ce projet.

**Comment by rgaudin** [comment]
@drcamara merci de créer une issue par problème, sinon on ne peut pas suivre facilement.

Pour le premier point, si, il est parfaitement possible de créer un compte Central sur mali, c'est même le cas de la majorité des comptes centraux.

Pour l'annuaire, les comptes utilisateurs ne sont pas attachés à des projets bien évidement. Le premier filtre agit sur les localités. Pour connaitre les comptes central, pas besoin de selectionner de projet.
