### ISSUE TITLE
Ajout de privilège au SNISI

### ISSUE THREAD

**Issue by alou** [yeleman/snisi#67]
# Nut
* Les points focaux Nut des districts deviennent des chargés Nut (peut envoyer le rapport SMS/EXCEL)au niveau de leur unité sanitaire;
* On leur  donne le privilège de Point focal Nut sur leur district (peut voir les données du district)

# Palu
* On donne le rôle de point focal palu (peut envoyer les rapport Excel) à tous ce que l'on avait considéré comme chargé SIS dans le PNLP

# Monitoring
prise en compte dans le #57

**Comment by rgaudin** [comment]
Fait.
@alou, merci de préparer les fichiers de move et privileges correspondant: chargés nut, pf_nut, pf_palu et dc_monitor.

**Comment by alou** [comment]
le fichier est prêt, il se trouve dans SNISI/utilisateur-SNISI-privilege.csv

**Comment by rgaudin** [comment]
Fait.
