### ISSUE TITLE
Désactivation d'un utilisateur SNISI

### ISSUE THREAD

**Issue by alou** [yeleman/snisi#69]
Dans l'action disable supprimer le numéro flotte

**Comment by rgaudin** [comment]
Est-ce que c'est systématique ? Si c'est un numéro personnel qui a été intégré à la flotte ? On a aucun moyen de savoir ça.
Est-ce que ce serait pas mieux d'avoir un moyen de supprimer des numéros de tél indépendamment ?

**Comment by alou** [comment]
Oui il est mieux de supprimer des numéros de tel indépendamment. 
Faire une interface qui permet de déplacer un numéro d'une personne 1 à une personne 2.
