### ISSUE TITLE
Problème d'enregistrement des intrants dans l'appli Android

### ISSUE THREAD

**Issue by alou** [yeleman/snisi#70]
Une fois que l'on supprime la base de données quand on constate le problème, il est résolu.
Il faut tester l'appli

**Comment by rgaudin** [comment]
FYI, commentaires de Seyon:
* rencontré le problème dans 10 CSCom.
* Tous avaient envoyé un rapport avec succès.
* Il a pu *débloquer* le problème en changeant les nombres. Il pensait que les stocks initiaux devaient correspondre au stocks finaux du mois précédent…
