### ISSUE TITLE
Armoniser le nom des établissements sanitaires dans les differents export Excel

### ISSUE THREAD

**Issue by alou** [yeleman/snisi#78]
Mettre le nom de l'unité sanitaire et son code entre parenthèse. Exemple: KOULIKORO (4JN7)

# Paludisme
* Données brutes 

        Région
        District
        Unité Sanitaire

# Nutrition
* Surveillance Hebdo. 

        Région
        District
        Unité Sanitaire
* Rapports Sources

        Région
        District
        Unité Sanitaire

# Santé Reproduction
* Données brutes MSI/PF

        Région
        District
        Unité Sanitaire

**Comment by rgaudin** [comment]
Pour epidémiologie, on a mis le nom et le code SNISI dans des cellules différentes. Ça me semble un bon comportement.

je propose d'harmoniser avec seulement 2 champs:
* Localité : Le nom du CSCom avec district et région si applicable.
* Code SNISI : le code de l'entité concernée

exemples:
* `DIAMARABOUGOU/DS MARKALA/RS SÉGOU` `S5C4`
* `DS MARKALA/RS SÉGOU` `HDF9`
* `RS SÉGOU` `2232`
* `MALI` `mali`

**Comment by fadiga** [comment]
Export xls:
Rapport Routine Paludisme mensuelle Données brutes.
Santé Reproduction mensuelle Données brutes MSI/PF.
Rapport Routine Nutrition mensuelle + hebdomadaire Données brutes.

On été harmonisé.
