### ISSUE TITLE
Modifications rapport MalariaR

### ISSUE THREAD

**Issue by rgaudin** [yeleman/snisi#82]
* Ajouter champ pour `pw_simple_malaria_cases` avec `default=0` + migration
* Modifier edit_report html
* Modifier integrity check
* Modifier raw_data html
* Modifier template rapport Excel
* Modifier template rapport PDF
* Modifier Export Excel
* Modifier SMS `mr m`
* Modifier Application J2ME (@fadiga)

**Comment by rgaudin** [comment]
Détails J2ME pour @fadiga :
 * Ajouter cas simples FE
 * Modifier check confirmés/casgraves/cassimples
 * Changer label `SP2` -> `SP2 et +`
 * Utiliser nouveau format SMS

**Comment by fadiga** [comment]
Malaria monthly
- smsKeyword = 'mr m'
- SPACER = " "

- Format SMS
`smsKeyword` + `SPACER`+
`username` + `SPACER`+
`password` + `SPACER`+
`u5_total_consultation` + `SPACER`+
`u5_total_malaria_cases` + `SPACER`+
`u5_total_tested_malaria_cases` + `SPACER`+
`u5_total_confirmed_malaria_cases` + `SPACER`+
`u5_total_simple_malaria_cases` + `SPACER`+
`u5_total_severe_malaria_cases` + `SPACER`+
`u5_total_acttreated_malaria_cases` + `SPACER`+
`u5_total_inpatient` + `SPACER`+
`u5_total_malaria_impatient` + `SPACER`+
`u5_total_death` + `SPACER`+
`u5_total_malaria_death` + `SPACER`+
`u5_malaria_total_distributed_bednets` + `SPACER`+
`o5_total_consultation` + `SPACER`+
`o5_total_malaria_cases` + `SPACER`+
`o5_total_tested_malaria_cases` + `SPACER`+
`o5_total_confirmed_malaria_cases` + `SPACER`+
`o5_total_simple_malaria_cases` + `SPACER`+
`o5_total_severe_malaria_cases` + `SPACER`+
`o5_total_acttreated_malaria_cases` + `SPACER`+
`o5_total_inpatient` + `SPACER`+
`o5_total_malaria_impatient` + `SPACER`+
`o5_total_death` + `SPACER`+
`o5_total_malaria_death` + `SPACER`+
`pw_total_consultation` + `SPACER`+
`pw_total_malaria_cases` + `SPACER`+
`pw_total_tested_malaria_cases` + `SPACER`+
`pw_total_confirmed_malaria_cases` + `SPACER`+
`pw_total_simple_malaria_cases` + `SPACER`+
`pw_total_severe_malaria_cases` + `SPACER`+
`pw_total_acttreated_malaria_cases` + `SPACER`+
`pw_total_inpatient` + `SPACER`+
`pw_total_malaria_impatient` + `SPACER`+
`pw_total_death` + `SPACER`+
`pw_total_malaria_death` + `SPACER`+
`pw_malaria_total_distributed_bednets` + `SPACER`+
`malaria_total_anc_1` + `SPACER`+
`malaria_total_sp_1` + `SPACER`+
`malaria_total_sp_2` + `SPACER`+
`malaria_stockout_act_children` + `SPACER`+
`malaria_stockout_act_youth` + `SPACER`+
`malaria_stockout_act_adult` + `SPACER`+
`malaria_stockout_artemether` + `SPACER`+
`malaria_stockout_quinine` + `SPACER`+
`malaria_stockout_serum` + `SPACER`+
`malaria_stockout_bednet` + `SPACER`+
`malaria_stockout_rdt` + `SPACER`+
`malaria_stockout_sp` + `SPACER`+

**Comment by fadiga** [comment]
Changements du J2ME :

- Ajout du champs cas simples FE.
- Check confirmés/casgraves/cassimples
- Changement de label SP2 -> SP2 et +
- Utilisation du nouveau format SMS

**Comment by rgaudin** [comment]
Update…
- [X] Ajouter champ pour `pw_simple_malaria_cases` avec `default=0` + migration
- [ ] Modifier edit_report html
- [ ] Modifier integrity check
- [ ] Modifier raw_data html
- [X] Modifier template rapport Excel
- [X] Modifier template rapport PDF
- [ ] Modifier Export Excel
- [ ] Modifier SMS `mr m`
- [X] Modifier Application J2ME (@fadiga)
- [X] Modifier Application Android

**Comment by rgaudin** [comment]
Update…
- [X] Ajouter champ pour `pw_simple_malaria_cases` avec `default=0` + migration
- [X] Modifier edit_report html
- [X] Modifier integrity check
- [X] Modifier raw_data html
- [X] Modifier template rapport Excel
- [X] Modifier template rapport PDF
- [X] Modifier Export Excel
- [ ] Modifier SMS `mr m`
- [X] Modifier Application J2ME (@fadiga)
- [X] Modifier Application Android

**Comment by rgaudin** [comment]
Completed with 67894ea

Actual SMS format (proper variable names):
```
kw1 + SPACER +
kw2 + SPACER +
username + SPACER +
password + SPACER +
u5_total_consultation_all_causes + SPACER +
u5_total_suspected_malaria_cases + SPACER +
u5_total_simple_malaria_cases + SPACER +
u5_total_severe_malaria_cases + SPACER +
u5_total_tested_malaria_cases + SPACER +
u5_total_confirmed_malaria_cases + SPACER +
u5_total_treated_malaria_cases + SPACER +
u5_total_inpatient_all_causes + SPACER +
u5_total_malaria_inpatient + SPACER +
u5_total_death_all_causes + SPACER +
u5_total_malaria_death + SPACER +
u5_total_distributed_bednets + SPACER +
o5_total_consultation_all_causes + SPACER +
o5_total_suspected_malaria_cases + SPACER +
o5_total_simple_malaria_cases + SPACER +
o5_total_severe_malaria_cases + SPACER +
o5_total_tested_malaria_cases + SPACER +
o5_total_confirmed_malaria_cases + SPACER +
o5_total_treated_malaria_cases + SPACER +
o5_total_inpatient_all_causes + SPACER +
o5_total_malaria_inpatient + SPACER +
o5_total_death_all_causes + SPACER +
o5_total_malaria_death + SPACER +
pw_total_consultation_all_causes + SPACER +
pw_total_suspected_malaria_cases + SPACER +
pw_total_simple_malaria_cases + SPACER +
pw_total_severe_malaria_cases + SPACER +
pw_total_tested_malaria_cases + SPACER +
pw_total_confirmed_malaria_cases + SPACER +
pw_total_treated_malaria_cases + SPACER +
pw_total_inpatient_all_causes + SPACER +
pw_total_malaria_inpatient + SPACER +
pw_total_death_all_causes + SPACER +
pw_total_malaria_death + SPACER +
pw_total_distributed_bednets + SPACER +
pw_total_anc1 + SPACER +
pw_total_sp1 + SPACER +
pw_total_sp2 + SPACER +
stockout_act_children + SPACER +
stockout_act_youth + SPACER +
stockout_act_adult + SPACER +
stockout_artemether + SPACER +
stockout_quinine + SPACER +
stockout_serum + SPACER +
stockout_bednet + SPACER +
stockout_rdt + SPACER +
stockout_sp```
